# Form implementation generated from reading ui file 'D:\học đhoc\Hoc ky 2\Kỹ thuật lập trình\3nguoi\ui\Khach_hang\thanhtoan\Thanhtoan.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(803, 729)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\học đhoc\\Hoc ky 2\\Kỹ thuật lập trình\\3nguoi\\ui\\Khach_hang\\thanhtoan\\../../../images/skibidi.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 40, 211, 51))
        self.label.setStyleSheet("color: rgb(4, 140, 252);\n"
"border-radius: 15px;\n"
"padding: 5px;\n"
"background-color: rgb(211, 234, 255);")
        self.label.setObjectName("label")
        self.Xacnhanbutton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Xacnhanbutton.setGeometry(QtCore.QRect(270, 590, 241, 51))
        self.Xacnhanbutton.setStyleSheet("QPushButton {\n"
"    /* Kiểu mặc định của nút */\n"
"background-color: rgb(102, 187, 106);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 15pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"border: 1px solid #048cfc;\n"
"}\n"
"\n"
"/* Khi di chuột qua nút */\n"
"QPushButton:hover {\n"
"background-color: rgb(84, 187, 91);\n"
"}\n"
"\n"
"/* Khi nhấn nút */\n"
"QPushButton:pressed {\n"
"background-color: rgb(44, 195, 49);\n"
"    /* Bạn có thể thay đổi màu chữ, viền... nếu muốn */\n"
"}")
        self.Xacnhanbutton.setObjectName("Xacnhanbutton")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(60, 110, 681, 411))
        self.scrollArea.setStyleSheet("\n"
"background-color: #F0F8FF;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: #048cfc;\n"
"border-radius: 10px;\n"
"border: 1px solid #048cfc;\n"
"\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 679, 409))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hoadonthanhtoanwidget = QtWidgets.QTableWidget(parent=self.scrollAreaWidgetContents)
        self.hoadonthanhtoanwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.hoadonthanhtoanwidget.setStyleSheet("\n"
"background-color: #F0F8FF;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: #048cfc;\n"
"border-radius: 10px;\n"
"border: 1px solid #048cfc;\n"
"\n"
"")
        self.hoadonthanhtoanwidget.setObjectName("hoadonthanhtoanwidget")
        self.hoadonthanhtoanwidget.setColumnCount(4)
        self.hoadonthanhtoanwidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.hoadonthanhtoanwidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hoadonthanhtoanwidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.hoadonthanhtoanwidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.hoadonthanhtoanwidget.setHorizontalHeaderItem(3, item)
        self.hoadonthanhtoanwidget.horizontalHeader().setCascadingSectionResizes(True)
        self.hoadonthanhtoanwidget.horizontalHeader().setDefaultSectionSize(158)
        self.hoadonthanhtoanwidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.hoadonthanhtoanwidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 540, 121, 31))
        self.label_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.Thanhtien = QtWidgets.QLabel(parent=self.centralwidget)
        self.Thanhtien.setGeometry(QtCore.QRect(180, 540, 561, 31))
        self.Thanhtien.setStyleSheet("\n"
"background-color: #F0F8FF;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: #048cfc;\n"
"border-radius: 10px;\n"
"border: 1px solid #048cfc;\n"
"\n"
"")
        self.Thanhtien.setText("")
        self.Thanhtien.setObjectName("Thanhtien")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(-310, -230, 1111, 1201))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("D:\\học đhoc\\Hoc ky 2\\Kỹ thuật lập trình\\3nguoi\\ui\\Khach_hang\\thanhtoan\\../../../images/backround.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.label.raise_()
        self.Xacnhanbutton.raise_()
        self.scrollArea.raise_()
        self.label_2.raise_()
        self.Thanhtien.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Skibidi Water"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:696; color:#048cfc;\">Hóa đơn thanh toán</span></p></body></html>"))
        self.Xacnhanbutton.setText(_translate("MainWindow", "Xác nhận thanh toán"))
        item = self.hoadonthanhtoanwidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Tên"))
        item = self.hoadonthanhtoanwidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Size"))
        item = self.hoadonthanhtoanwidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Đơn giá"))
        item = self.hoadonthanhtoanwidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Số lượng"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:696; color:#048cfc;\">Thành tiền:</span></p></body></html>"))
