# Form implementation generated from reading ui file '3nguoi\ui\Khach_hang\thanhtoan\Xacnhanthanhtoan.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(791, 815)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("3nguoi\\ui\\Khach_hang\\thanhtoan\\../../../images/skibidi.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 80, 461, 641))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("3nguoi\\ui\\Khach_hang\\thanhtoan\\../../../images/Screenshot 2025-03-22 174809.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 270, 191, 191))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("3nguoi\\ui\\Khach_hang\\thanhtoan\\../../../images/Screenshot 2025-03-22 174353.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.Dangkybutton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Dangkybutton.setGeometry(QtCore.QRect(310, 650, 181, 51))
        self.Dangkybutton.setStyleSheet("border-radius: 10px;\n"
"")
        self.Dangkybutton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("3nguoi\\ui\\Khach_hang\\thanhtoan\\../../../images/Screenshot 2025-03-22 180342.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Dangkybutton.setIcon(icon1)
        self.Dangkybutton.setIconSize(QtCore.QSize(200, 200))
        self.Dangkybutton.setDefault(False)
        self.Dangkybutton.setFlat(True)
        self.Dangkybutton.setObjectName("Dangkybutton")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(-100, -20, 891, 821))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("3nguoi\\ui\\Khach_hang\\thanhtoan\\../../../../../../../Download/3nguoi/images/backround.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.HomeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.HomeButton.setGeometry(QtCore.QRect(0, 0, 41, 31))
        self.HomeButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("3nguoi\\ui\\Khach_hang\\thanhtoan\\../../../images/Home.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.HomeButton.setIcon(icon2)
        self.HomeButton.setObjectName("HomeButton")
        self.label_10.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.Dangkybutton.raise_()
        self.HomeButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Skibidi Water"))
