# Form implementation generated from reading ui file 'D:\học đhoc\Hoc ky 2\Kỹ thuật lập trình\3nguoi\ui\Quanly\ThongKeWindow\thongke.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1070, 827)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\học đhoc\\Hoc ky 2\\Kỹ thuật lập trình\\3nguoi\\ui\\Quanly\\ThongKeWindow\\../../../images/skibidi.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.thongkeLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.thongkeLabel.setGeometry(QtCore.QRect(10, 200, 1051, 591))
        self.thongkeLabel.setStyleSheet("\n"
"background-color: #F0F8FF;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: #048cfc;\n"
"border-radius: 10px;\n"
"border: 1px solid #048cfc;\n"
"\n"
"")
        self.thongkeLabel.setText("")
        self.thongkeLabel.setObjectName("thongkeLabel")
        self.LoaiDonHangcombobox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.LoaiDonHangcombobox.setGeometry(QtCore.QRect(10, 130, 211, 22))
        self.LoaiDonHangcombobox.setStyleSheet("\n"
"background-color: #F0F8FF;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: #048cfc;\n"
"border-radius: 10px;\n"
"border: 1px solid #048cfc;\n"
"\n"
"")
        self.LoaiDonHangcombobox.setObjectName("LoaiDonHangcombobox")
        self.LoaiDonHangcombobox.addItem("")
        self.LoaiDonHangcombobox.addItem("")
        self.LoaiDonHangcombobox.addItem("")
        self.LoaiDonHangcombobox.addItem("")
        self.LoaiDonHangcombobox.addItem("")
        self.LoaiDonHangcombobox.addItem("")
        self.LoaiDonHangcombobox.addItem("")
        self.LoaiDonHangcombobox.addItem("")
        self.LoaiDonHangcombobox.addItem("")
        self.LoaiDonHangcombobox.addItem("")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 110, 221, 21))
        self.label.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: #048cfc;\n"
"\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(420, 110, 221, 21))
        self.label_2.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: #048cfc;\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(820, 110, 221, 21))
        self.label_3.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: #048cfc;\n"
"\n"
"")
        self.label_3.setObjectName("label_3")
        self.StarttimeEdit = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.StarttimeEdit.setGeometry(QtCore.QRect(420, 130, 191, 22))
        self.StarttimeEdit.setStyleSheet("\n"
"background-color: #F0F8FF;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: #048cfc;\n"
"border-radius: 10px;\n"
"border: 1px solid #048cfc;\n"
"\n"
"")
        self.StarttimeEdit.setCalendarPopup(True)
        self.StarttimeEdit.setDate(QtCore.QDate(2025, 3, 20))
        self.StarttimeEdit.setObjectName("StarttimeEdit")
        self.EndtimeEdit = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.EndtimeEdit.setGeometry(QtCore.QRect(820, 130, 191, 22))
        self.EndtimeEdit.setStyleSheet("\n"
"background-color: #F0F8FF;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: #048cfc;\n"
"border-radius: 10px;\n"
"border: 1px solid #048cfc;\n"
"\n"
"")
        self.EndtimeEdit.setCalendarPopup(True)
        self.EndtimeEdit.setDate(QtCore.QDate(2025, 3, 25))
        self.EndtimeEdit.setObjectName("EndtimeEdit")
        self.HomeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.HomeButton.setGeometry(QtCore.QRect(0, 0, 31, 28))
        self.HomeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\học đhoc\\Hoc ky 2\\Kỹ thuật lập trình\\3nguoi\\ui\\Quanly\\ThongKeWindow\\../../../images/Home.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.HomeButton.setIcon(icon1)
        self.HomeButton.setObjectName("HomeButton")
        self.comboBoxhinhthuc = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBoxhinhthuc.setGeometry(QtCore.QRect(10, 170, 101, 22))
        self.comboBoxhinhthuc.setStyleSheet("\n"
"background-color: #F0F8FF;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: #048cfc;\n"
"border-radius: 10px;\n"
"border: 1px solid #048cfc;\n"
"\n"
"")
        self.comboBoxhinhthuc.setObjectName("comboBoxhinhthuc")
        self.comboBoxhinhthuc.addItem("")
        self.comboBoxhinhthuc.addItem("")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(390, 20, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(4, 140, 252);\n"
"border-radius: 15px;\n"
"padding: 5px;\n"
"background-color: rgb(211, 234, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 110, 241, 51))
        self.label_6.setStyleSheet("\n"
"background-color: #F0F8FF;\n"
"border-radius: 10px;\n"
"border: 1px solid #048cfc;\n"
"\n"
"")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(410, 110, 241, 51))
        self.label_7.setStyleSheet("\n"
"background-color: #F0F8FF;\n"
"border-radius: 10px;\n"
"border: 1px solid #048cfc;\n"
"\n"
"")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(810, 110, 241, 51))
        self.label_8.setStyleSheet("\n"
"background-color: #F0F8FF;\n"
"border-radius: 10px;\n"
"border: 1px solid #048cfc;\n"
"\n"
"")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(-16, -35, 1091, 851))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.label_8.raise_()
        self.label_7.raise_()
        self.label_6.raise_()
        self.thongkeLabel.raise_()
        self.LoaiDonHangcombobox.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.StarttimeEdit.raise_()
        self.EndtimeEdit.raise_()
        self.HomeButton.raise_()
        self.comboBoxhinhthuc.raise_()
        self.label_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1070, 26))
        self.menubar.setObjectName("menubar")
        self.menuExport_to_Excel = QtWidgets.QMenu(parent=self.menubar)
        self.menuExport_to_Excel.setObjectName("menuExport_to_Excel")
        MainWindow.setMenuBar(self.menubar)
        self.actionExport_to_Excel = QtGui.QAction(parent=MainWindow)
        self.actionExport_to_Excel.setObjectName("actionExport_to_Excel")
        self.menuExport_to_Excel.addAction(self.actionExport_to_Excel)
        self.menubar.addAction(self.menuExport_to_Excel.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Skibidi Water"))
        self.LoaiDonHangcombobox.setItemText(0, _translate("MainWindow", "Tất cả"))
        self.LoaiDonHangcombobox.setItemText(1, _translate("MainWindow", "Cà Phê"))
        self.LoaiDonHangcombobox.setItemText(2, _translate("MainWindow", "Trà Sữa"))
        self.LoaiDonHangcombobox.setItemText(3, _translate("MainWindow", "Nước Ép"))
        self.LoaiDonHangcombobox.setItemText(4, _translate("MainWindow", "Sinh Tố"))
        self.LoaiDonHangcombobox.setItemText(5, _translate("MainWindow", "Đá Xay"))
        self.LoaiDonHangcombobox.setItemText(6, _translate("MainWindow", "Soda"))
        self.LoaiDonHangcombobox.setItemText(7, _translate("MainWindow", "Trà Trái Cây"))
        self.LoaiDonHangcombobox.setItemText(8, _translate("MainWindow", "Nước Ngọt"))
        self.LoaiDonHangcombobox.setItemText(9, _translate("MainWindow", "Khác"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Loại đơn hàng</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Thời gian bắt đầu</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Thời gian kết thúc</span></p></body></html>"))
        self.StarttimeEdit.setDisplayFormat(_translate("MainWindow", "d/M/yyyy"))
        self.EndtimeEdit.setDisplayFormat(_translate("MainWindow", "d/M/yyyy"))
        self.comboBoxhinhthuc.setItemText(0, _translate("MainWindow", "Tổng quan"))
        self.comboBoxhinhthuc.setItemText(1, _translate("MainWindow", "Chi tiết"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:696; color:#048cfc;\">Thống kê thu nhập</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.menuExport_to_Excel.setTitle(_translate("MainWindow", "Data"))
        self.actionExport_to_Excel.setText(_translate("MainWindow", "Export to Excel"))
