# Form implementation generated from reading ui file '3nguoi\ui\Quanly\QuanLyMenu\Menu.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(776, 485)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("3nguoi\\ui\\Quanly\\QuanLyMenu\\../../../images/skibidi.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(390, 70, 341, 411))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    background-color: #F0F8FF;\n"
"    border: 21px #048cfc;\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"}\n"
"QGroupBox::title {\n"
"    color: #048cfc;\n"
"    font-weight: bold;\n"
"    padding: 5px;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMaximumSize(QtCore.QSize(600, 1000))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("    background-color: #F0F8FF;\n"
"color: #048cfc;\n"
"border-radius: 10px;\n"
"border: 1px solid #048cfc")
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 311, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(4, 140, 252);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"border-radius: 12px;\n"
"padding: 5px;\n"
"background-color: #F0F8FF;")
        self.label_2.setObjectName("label_2")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 140, 321, 201))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("background-color: #F0F8FF;\n"
"color: #048cfc;\n"
"border-radius: 10px;\n"
"border: 1px solid #048cfc")
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEditNhapTenSanPham = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.lineEditNhapTenSanPham.setGeometry(QtCore.QRect(130, 70, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditNhapTenSanPham.setFont(font)
        self.lineEditNhapTenSanPham.setStyleSheet("    border-radius: 5px;\n"
"    padding: 5px;")
        self.lineEditNhapTenSanPham.setObjectName("lineEditNhapTenSanPham")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("    border-radius: 7px;\n"
"    padding: 5px;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("    border-radius: 7px;\n"
"    padding: 5px;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 150, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("    border-radius: 7px;\n"
"    padding: 5px;")
        self.label_6.setObjectName("label_6")
        self.comboBox_LoaiDoUong = QtWidgets.QComboBox(parent=self.groupBox_3)
        self.comboBox_LoaiDoUong.setGeometry(QtCore.QRect(130, 30, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_LoaiDoUong.setFont(font)
        self.comboBox_LoaiDoUong.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.comboBox_LoaiDoUong.setObjectName("comboBox_LoaiDoUong")
        self.comboBox_LoaiDoUong.addItem("")
        self.comboBox_LoaiDoUong.setItemText(0, "")
        self.comboBox_LoaiDoUong.addItem("")
        self.comboBox_LoaiDoUong.addItem("")
        self.comboBox_LoaiDoUong.addItem("")
        self.comboBox_LoaiDoUong.addItem("")
        self.comboBox_LoaiDoUong.addItem("")
        self.comboBox_LoaiDoUong.addItem("")
        self.comboBox_LoaiDoUong.addItem("")
        self.comboBox_LoaiDoUong.addItem("")
        self.comboBox_LoaiDoUong.addItem("")
        self.lineEditGia = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.lineEditGia.setGeometry(QtCore.QRect(130, 150, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditGia.setFont(font)
        self.lineEditGia.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.lineEditGia.setStyleSheet("    border-radius: 5px;\n"
"    padding: 5px;")
        self.lineEditGia.setObjectName("lineEditGia")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(10, 110, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("    border-radius: 7px;\n"
"    padding: 5px;")
        self.label_7.setObjectName("label_7")
        self.comboBox_SizeDoUong = QtWidgets.QComboBox(parent=self.groupBox_3)
        self.comboBox_SizeDoUong.setGeometry(QtCore.QRect(130, 110, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_SizeDoUong.setFont(font)
        self.comboBox_SizeDoUong.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.comboBox_SizeDoUong.setObjectName("comboBox_SizeDoUong")
        self.comboBox_SizeDoUong.addItem("")
        self.comboBox_SizeDoUong.addItem("")
        self.comboBox_LocSanPhamTheoDanhMuc = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox_LocSanPhamTheoDanhMuc.setGeometry(QtCore.QRect(250, 80, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_LocSanPhamTheoDanhMuc.setFont(font)
        self.comboBox_LocSanPhamTheoDanhMuc.setStyleSheet("background-color: #F0F8FF;\n"
"color: #048cfc;\n"
"border-radius: 10px;\n"
"border: 1px solid #048cfc")
        self.comboBox_LocSanPhamTheoDanhMuc.setObjectName("comboBox_LocSanPhamTheoDanhMuc")
        self.comboBox_LocSanPhamTheoDanhMuc.addItem("")
        self.comboBox_LocSanPhamTheoDanhMuc.addItem("")
        self.comboBox_LocSanPhamTheoDanhMuc.addItem("")
        self.comboBox_LocSanPhamTheoDanhMuc.addItem("")
        self.comboBox_LocSanPhamTheoDanhMuc.addItem("")
        self.comboBox_LocSanPhamTheoDanhMuc.addItem("")
        self.HomeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.HomeButton.setGeometry(QtCore.QRect(0, 0, 41, 31))
        self.HomeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("3nguoi\\ui\\Quanly\\QuanLyMenu\\../../../images/Home.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.HomeButton.setIcon(icon1)
        self.HomeButton.setObjectName("HomeButton")
        self.pushButton_ChinhSua = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_ChinhSua.setGeometry(QtCore.QRect(200, 360, 151, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_ChinhSua.setFont(font)
        self.pushButton_ChinhSua.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_ChinhSua.setStyleSheet("QPushButton {\n"
"    background-color: #048cfc;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #026bb3;\n"
"}\n"
"    font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_ChinhSua.setObjectName("pushButton_ChinhSua")
        self.pushButton_ThemSP = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_ThemSP.setGeometry(QtCore.QRect(40, 360, 141, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_ThemSP.setFont(font)
        self.pushButton_ThemSP.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_ThemSP.setStyleSheet("QPushButton {\n"
"    background-color: #048cfc;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #026bb3;\n"
"}\n"
"    font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_ThemSP.setIconSize(QtCore.QSize(170, 80))
        self.pushButton_ThemSP.setObjectName("pushButton_ThemSP")
        self.pushButton_Xoa = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Xoa.setGeometry(QtCore.QRect(200, 410, 151, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_Xoa.setFont(font)
        self.pushButton_Xoa.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_Xoa.setStyleSheet("QPushButton {\n"
"    background-color: #048cfc;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #026bb3;\n"
"}\n"
"    font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_Xoa.setObjectName("pushButton_Xoa")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 791, 481))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("3nguoi\\ui\\Quanly\\QuanLyMenu\\../../../images/backround.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(244, 0, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(4, 140, 252);\n"
"border-radius: 15px;\n"
"padding: 5px;\n"
"background-color: rgb(211, 234, 255);")
        self.label.setObjectName("label")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(390, 60, 331, 21))
        self.label_8.setAutoFillBackground(False)
        self.label_8.setScaledContents(False)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(44, 359, 131, 31))
        self.label_9.setObjectName("label_9")
        self.label_3.raise_()
        self.label_9.raise_()
        self.groupBox.raise_()
        self.label_2.raise_()
        self.groupBox_3.raise_()
        self.comboBox_LocSanPhamTheoDanhMuc.raise_()
        self.HomeButton.raise_()
        self.pushButton_ChinhSua.raise_()
        self.pushButton_ThemSP.raise_()
        self.pushButton_Xoa.raise_()
        self.label.raise_()
        self.label_8.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 776, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Skibidi Water"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sản phẩm"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Size"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Giá"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:696; color:#048cfc;\">Lọc sản phẩm theo danh mục:</span></p></body></html>"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Nhập liệu và quản lý sản phẩm:"))
        self.lineEditNhapTenSanPham.setPlaceholderText(_translate("MainWindow", "Nhập tên của sản phẩm"))
        self.label_4.setText(_translate("MainWindow", "Tên sản phẩm:"))
        self.label_5.setText(_translate("MainWindow", "Danh mục:"))
        self.label_6.setText(_translate("MainWindow", "Giá:"))
        self.comboBox_LoaiDoUong.setItemText(1, _translate("MainWindow", "Trà sữa"))
        self.comboBox_LoaiDoUong.setItemText(2, _translate("MainWindow", "Cà phê"))
        self.comboBox_LoaiDoUong.setItemText(3, _translate("MainWindow", "Đá Xay"))
        self.comboBox_LoaiDoUong.setItemText(4, _translate("MainWindow", "Soda"))
        self.comboBox_LoaiDoUong.setItemText(5, _translate("MainWindow", "Nước Ép"))
        self.comboBox_LoaiDoUong.setItemText(6, _translate("MainWindow", "Sinh Tố"))
        self.comboBox_LoaiDoUong.setItemText(7, _translate("MainWindow", "Nước Ngọt"))
        self.comboBox_LoaiDoUong.setItemText(8, _translate("MainWindow", "Trà Trái Cây"))
        self.comboBox_LoaiDoUong.setItemText(9, _translate("MainWindow", "Khác"))
        self.lineEditGia.setPlaceholderText(_translate("MainWindow", "Giá sản phẩm nghìn VND"))
        self.label_7.setText(_translate("MainWindow", "Size:"))
        self.comboBox_SizeDoUong.setToolTip(_translate("MainWindow", "<html><head/><body><p>Đơn vị ml</p></body></html>"))
        self.comboBox_SizeDoUong.setItemText(0, _translate("MainWindow", "700"))
        self.comboBox_SizeDoUong.setItemText(1, _translate("MainWindow", "1000"))
        self.comboBox_LocSanPhamTheoDanhMuc.setItemText(0, _translate("MainWindow", "Tất cả"))
        self.comboBox_LocSanPhamTheoDanhMuc.setItemText(1, _translate("MainWindow", "Sinh tố"))
        self.comboBox_LocSanPhamTheoDanhMuc.setItemText(2, _translate("MainWindow", "Nước ngọt"))
        self.comboBox_LocSanPhamTheoDanhMuc.setItemText(3, _translate("MainWindow", "Cà phê"))
        self.comboBox_LocSanPhamTheoDanhMuc.setItemText(4, _translate("MainWindow", "Nước ép"))
        self.comboBox_LocSanPhamTheoDanhMuc.setItemText(5, _translate("MainWindow", "Trà"))
        self.pushButton_ChinhSua.setText(_translate("MainWindow", "Chỉnh sửa"))
        self.pushButton_ThemSP.setText(_translate("MainWindow", "Thêm sản phẩm"))
        self.pushButton_Xoa.setText(_translate("MainWindow", "Xóa sản phẩm"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:696; color:#048cfc;\">Menu Management</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:696; color:#048cfc;\">Danh sách sản phẩm:</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:696; color:#ffffff;\">Thêm sản phẩm</span></p></body></html>"))
