# Form implementation generated from reading ui file 'D:\học đhoc\Hoc ky 2\Kỹ thuật lập trình\3nguoi\ui\Khach_hang\Menu\MainWindowMenuOrder.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1002, 617)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777200))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\học đhoc\\Hoc ky 2\\Kỹ thuật lập trình\\3nguoi\\ui\\Khach_hang\\Menu\\../../../images/skibidi.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(500, 16777215))
        self.tabWidget.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.scrollArea_3 = QtWidgets.QScrollArea(parent=self.tab)
        self.scrollArea_3.setStyleSheet("background-color: rgb(179, 229, 252);")
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 470, 530))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_42 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_3)
        self.frame_42.setMaximumSize(QtCore.QSize(150, 180))
        self.frame_42.setStyleSheet("background-color: rgb(4, 140, 252);\n"
"border-raidus: 10px")
        self.frame_42.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_42.setLineWidth(3)
        self.frame_42.setObjectName("frame_42")
        self.verticalLayout_51 = QtWidgets.QVBoxLayout(self.frame_42)
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.label_93 = QtWidgets.QLabel(parent=self.frame_42)
        self.label_93.setStyleSheet("border_radius: 5px")
        self.label_93.setText("")
        self.label_93.setPixmap(QtGui.QPixmap("D:\\học đhoc\\Hoc ky 2\\Kỹ thuật lập trình\\3nguoi\\ui\\Khach_hang\\Menu\\../images/ca_phe_sua.jpg"))
        self.label_93.setScaledContents(True)
        self.label_93.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_93.setObjectName("label_93")
        self.verticalLayout_51.addWidget(self.label_93)
        self.label_94 = QtWidgets.QLabel(parent=self.frame_42)
        self.label_94.setMinimumSize(QtCore.QSize(0, 20))
        self.label_94.setStyleSheet("background-color: rgb(208, 255, 222);\n"
"color: rgb(0, 0, 0);\n"
"\n"
"\n"
"border-radius: 5px\n"
"")
        self.label_94.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_94.setObjectName("label_94")
        self.verticalLayout_51.addWidget(self.label_94)
        self.label_95 = QtWidgets.QLabel(parent=self.frame_42)
        self.label_95.setMinimumSize(QtCore.QSize(0, 20))
        self.label_95.setStyleSheet("\n"
"color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(208, 255, 222);\n"
"border-radius: 5px\n"
"")
        self.label_95.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_95.setObjectName("label_95")
        self.verticalLayout_51.addWidget(self.label_95)
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_42)
        self.pushButton.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(0, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_51.addWidget(self.pushButton)
        self.gridLayout_9.addWidget(self.frame_42, 0, 0, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_9)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_10.addWidget(self.scrollArea_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setMaximumSize(QtCore.QSize(494, 16777215))
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea_2 = QtWidgets.QScrollArea(parent=self.tab_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 470, 530))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame_34 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_2)
        self.frame_34.setMaximumSize(QtCore.QSize(150, 180))
        self.frame_34.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-raidus: 10px")
        self.frame_34.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_34.setLineWidth(3)
        self.frame_34.setObjectName("frame_34")
        self.verticalLayout_43 = QtWidgets.QVBoxLayout(self.frame_34)
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.label_69 = QtWidgets.QLabel(parent=self.frame_34)
        self.label_69.setStyleSheet("border_radius: 5px")
        self.label_69.setText("")
        self.label_69.setPixmap(QtGui.QPixmap("D:\\học đhoc\\Hoc ky 2\\Kỹ thuật lập trình\\3nguoi\\ui\\Khach_hang\\Menu\\../images/7up.jpg"))
        self.label_69.setScaledContents(True)
        self.label_69.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_69.setObjectName("label_69")
        self.verticalLayout_43.addWidget(self.label_69)
        self.label_70 = QtWidgets.QLabel(parent=self.frame_34)
        self.label_70.setMinimumSize(QtCore.QSize(0, 20))
        self.label_70.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_70.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_70.setObjectName("label_70")
        self.verticalLayout_43.addWidget(self.label_70)
        self.label_71 = QtWidgets.QLabel(parent=self.frame_34)
        self.label_71.setMinimumSize(QtCore.QSize(0, 20))
        self.label_71.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_71.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_71.setObjectName("label_71")
        self.verticalLayout_43.addWidget(self.label_71)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_34)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_43.addWidget(self.pushButton_4)
        self.gridLayout_8.addWidget(self.frame_34, 0, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_8)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color: #F0F8FF;\n"
"color: #048cfc;\n"
"border-radius: 10px;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_61 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_61.setGeometry(QtCore.QRect(10, 80, 81, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_61.setFont(font)
        self.label_61.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_61.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_61.setObjectName("label_61")
        self.lineEditSoDienThoai = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditSoDienThoai.setGeometry(QtCore.QRect(170, 70, 251, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEditSoDienThoai.setFont(font)
        self.lineEditSoDienThoai.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid #048cfc")
        self.lineEditSoDienThoai.setPlaceholderText("")
        self.lineEditSoDienThoai.setObjectName("lineEditSoDienThoai")
        self.label_62 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_62.setGeometry(QtCore.QRect(10, 30, 171, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_62.setFont(font)
        self.label_62.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_62.setObjectName("label_62")
        self.lineEditTenKH = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditTenKH.setGeometry(QtCore.QRect(170, 30, 251, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEditTenKH.setFont(font)
        self.lineEditTenKH.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid #048cfc")
        self.lineEditTenKH.setObjectName("lineEditTenKH")
        self.labelTongTien = QtWidgets.QLabel(parent=self.groupBox)
        self.labelTongTien.setGeometry(QtCore.QRect(200, 390, 231, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelTongTien.setFont(font)
        self.labelTongTien.setAutoFillBackground(False)
        self.labelTongTien.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid #048cfc")
        self.labelTongTien.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.labelTongTien.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.labelTongTien.setMidLineWidth(3)
        self.labelTongTien.setText("")
        self.labelTongTien.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTongTien.setObjectName("labelTongTien")
        self.pushButtonThanhToan = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonThanhToan.setGeometry(QtCore.QRect(30, 470, 411, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButtonThanhToan.setFont(font)
        self.pushButtonThanhToan.setStyleSheet("QPushButton {\n"
"    /* Kiểu mặc định của nút */\n"
"background-color: rgb(102, 187, 106);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 15pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"/* Khi di chuột qua nút */\n"
"QPushButton:hover {\n"
"background-color: rgb(84, 187, 91);\n"
"}\n"
"\n"
"/* Khi nhấn nút */\n"
"QPushButton:pressed {\n"
"background-color: rgb(44, 195, 49);\n"
"    /* Bạn có thể thay đổi màu chữ, viền... nếu muốn */\n"
"}")
        self.pushButtonThanhToan.setObjectName("pushButtonThanhToan")
        self.label_63 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_63.setGeometry(QtCore.QRect(60, 390, 141, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_63.setFont(font)
        self.label_63.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_63.setObjectName("label_63")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 130, 461, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("\n"
"background-color: #F0F8FF;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: #048cfc;\n"
"border-radius: 10px;\n"
"border: 1px solid #048cfc;\n"
"\n"
"")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tableWidget.setItem(0, 3, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(0, 0, 151, 21))
        self.label.setObjectName("label")
        self.Quaylaibutton = QtWidgets.QPushButton(parent=self.groupBox)
        self.Quaylaibutton.setGeometry(QtCore.QRect(90, 540, 291, 28))
        self.Quaylaibutton.setStyleSheet("QPushButton {\n"
"    /* Kiểu mặc định của nút */\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"font: 75 15pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"/* Khi di chuột qua nút */\n"
"QPushButton:hover {\n"
"background-color: rgb(235, 235, 235);\n"
"}\n"
"\n"
"/* Khi nhấn nút */\n"
"QPushButton:pressed {\n"
"background-color: rgb(194, 194, 194);\n"
"    /* Bạn có thể thay đổi màu chữ, viền... nếu muốn */\n"
"}")
        self.Quaylaibutton.setObjectName("Quaylaibutton")
        self.label_62.raise_()
        self.label_61.raise_()
        self.lineEditSoDienThoai.raise_()
        self.lineEditTenKH.raise_()
        self.labelTongTien.raise_()
        self.pushButtonThanhToan.raise_()
        self.label_63.raise_()
        self.verticalLayoutWidget.raise_()
        self.label.raise_()
        self.Quaylaibutton.raise_()
        self.verticalLayout_4.addWidget(self.groupBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Skibidi Water"))
        self.label_94.setText(_translate("MainWindow", "Cà Phê Đen"))
        self.label_95.setText(_translate("MainWindow", "20000 VNĐ"))
        self.pushButton.setText(_translate("MainWindow", "Thêm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Cà Phê"))
        self.label_70.setText(_translate("MainWindow", "Cà Phê Đen"))
        self.label_71.setText(_translate("MainWindow", "20000 VNĐ"))
        self.pushButton_4.setText(_translate("MainWindow", "Thêm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Trà Sữa"))
        self.label_61.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:696; color:#048cfc;\">SĐT:</span></p></body></html>"))
        self.label_62.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:696; color:#048cfc;\">Tên khách hàng:</span></p></body></html>"))
        self.pushButtonThanhToan.setText(_translate("MainWindow", "Thanh Toán "))
        self.label_63.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:696; color:#048cfc;\">Tổng tiền:</span></p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Tên Sản Phẩm"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Giá "))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Số Lượng "))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Tổng giá"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:696; color:#048cfc;\">Cart</span></p></body></html>"))
        self.Quaylaibutton.setText(_translate("MainWindow", "Quay lại"))
