# Form implementation generated from reading ui file 'D:\học đhoc\Hoc ky 2\Kỹ thuật lập trình\3nguoi\ui\Quanly\QuanLyNhanVien\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(945, 729)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\học đhoc\\Hoc ky 2\\Kỹ thuật lập trình\\3nguoi\\ui\\Quanly\\QuanLyNhanVien\\../../../images/skibidi.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 90, 441, 331))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color: #F0F8FF;\n"
"color: #048cfc;\n"
"    padding: 10px;\n"
"border: 1px solid #048cfc")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_9.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"border: 0")
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 4, 0, 1, 1)
        self.lineEditTen = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditTen.setStyleSheet("border-radius: 10px;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border: 1px solid #048cfc")
        self.lineEditTen.setObjectName("lineEditTen")
        self.gridLayout_3.addWidget(self.lineEditTen, 0, 1, 1, 2)
        self.radNu = QtWidgets.QRadioButton(parent=self.groupBox)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.radNu.setFont(font)
        self.radNu.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.radNu.setChecked(True)
        self.radNu.setObjectName("radNu")
        self.gridLayout_3.addWidget(self.radNu, 4, 1, 1, 1)
        self.lineEditId = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditId.setStyleSheet("border-radius: 10px;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border: 1px solid #048cfc")
        self.lineEditId.setObjectName("lineEditId")
        self.gridLayout_3.addWidget(self.lineEditId, 1, 1, 1, 2)
        self.radNam = QtWidgets.QRadioButton(parent=self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radNam.setFont(font)
        self.radNam.setObjectName("radNam")
        self.gridLayout_3.addWidget(self.radNam, 4, 2, 1, 1)
        self.lineEditNgaysinh = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditNgaysinh.setStyleSheet("border-radius: 10px;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border: 1px solid #048cfc")
        self.lineEditNgaysinh.setObjectName("lineEditNgaysinh")
        self.gridLayout_3.addWidget(self.lineEditNgaysinh, 2, 1, 1, 2)
        self.lineEditChucvu = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditChucvu.setStyleSheet("border-radius: 10px;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border: 1px solid #048cfc")
        self.lineEditChucvu.setObjectName("lineEditChucvu")
        self.gridLayout_3.addWidget(self.lineEditChucvu, 3, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: 0")
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border:0")
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border: 0")
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("border: 0")
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_11.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 440, 451, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("background-color: #F0F8FF;\n"
"color: #048cfc;\n"
"border-radius: 10px;\n"
"border: 1px solid #048cfc")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonSave = QtWidgets.QPushButton(parent=self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonSave.setFont(font)
        self.pushButtonSave.setStyleSheet("QPushButton {\n"
"    /* Kiểu mặc định của nút */\n"
"background-color: #F0F8FF;\n"
"color: #048cfc;\n"
"    font: 16pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"border: 1px solid #048cfc;\n"
"}\n"
"\n"
"/* Khi di chuột qua nút */\n"
"QPushButton:hover {\n"
"    background-color: rgb(220, 236, 255);\n"
"}\n"
"\n"
"/* Khi nhấn nút */\n"
"QPushButton:pressed {\n"
"background-color: rgb(197, 227, 255);\n"
"    /* Bạn có thể thay đổi màu chữ, viền... nếu muốn */\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\học đhoc\\Hoc ky 2\\Kỹ thuật lập trình\\3nguoi\\ui\\Quanly\\QuanLyNhanVien\\images/ic_save.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSave.setIcon(icon1)
        self.pushButtonSave.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayout.addWidget(self.pushButtonSave)
        self.pushButtonNew = QtWidgets.QPushButton(parent=self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonNew.setFont(font)
        self.pushButtonNew.setStyleSheet("QPushButton {\n"
"    /* Kiểu mặc định của nút */\n"
"background-color: #F0F8FF;\n"
"color: #048cfc;\n"
"    font: 16pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"border: 1px solid #048cfc;\n"
"}\n"
"\n"
"/* Khi di chuột qua nút */\n"
"QPushButton:hover {\n"
"    background-color: rgb(220, 236, 255);\n"
"}\n"
"\n"
"/* Khi nhấn nút */\n"
"QPushButton:pressed {\n"
"background-color: rgb(197, 227, 255);\n"
"    /* Bạn có thể thay đổi màu chữ, viền... nếu muốn */\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\học đhoc\\Hoc ky 2\\Kỹ thuật lập trình\\3nguoi\\ui\\Quanly\\QuanLyNhanVien\\images/ic_add.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonNew.setIcon(icon2)
        self.pushButtonNew.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonNew.setObjectName("pushButtonNew")
        self.horizontalLayout.addWidget(self.pushButtonNew)
        self.pushButtonDelete = QtWidgets.QPushButton(parent=self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonDelete.setFont(font)
        self.pushButtonDelete.setStyleSheet("QPushButton {\n"
"    /* Kiểu mặc định của nút */\n"
"background-color: #F0F8FF;\n"
"color: #048cfc;\n"
"    font: 16pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"border: 1px solid #048cfc;\n"
"}\n"
"\n"
"/* Khi di chuột qua nút */\n"
"QPushButton:hover {\n"
"    background-color: rgb(220, 236, 255);\n"
"}\n"
"\n"
"/* Khi nhấn nút */\n"
"QPushButton:pressed {\n"
"background-color: rgb(197, 227, 255);\n"
"    /* Bạn có thể thay đổi màu chữ, viền... nếu muốn */\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:\\học đhoc\\Hoc ky 2\\Kỹ thuật lập trình\\3nguoi\\ui\\Quanly\\QuanLyNhanVien\\images/ic_delete.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonDelete.setIcon(icon3)
        self.pushButtonDelete.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.horizontalLayout.addWidget(self.pushButtonDelete)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.hienthibutton = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.hienthibutton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.hienthibutton.setStyleSheet("QPushButton {\n"
"    /* Kiểu mặc định của nút */\n"
"background-color: #F0F8FF;\n"
"color: #048cfc;\n"
"    font: 16pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"border: 1px solid #048cfc;\n"
"}\n"
"\n"
"/* Khi di chuột qua nút */\n"
"QPushButton:hover {\n"
"    background-color: rgb(220, 236, 255);\n"
"}\n"
"\n"
"/* Khi nhấn nút */\n"
"QPushButton:pressed {\n"
"background-color: rgb(197, 227, 255);\n"
"    /* Bạn có thể thay đổi màu chữ, viền... nếu muốn */\n"
"}")
        self.hienthibutton.setObjectName("hienthibutton")
        self.verticalLayout_2.addWidget(self.hienthibutton)
        self.gridLayout_7.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_18.setStyleSheet("border: 0")
        self.label_18.setObjectName("label_18")
        self.gridLayout_7.addWidget(self.label_18, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(470, 90, 461, 491))
        self.groupBox_2.setStyleSheet("background-color: #F0F8FF;\n"
"color: #048cfc;\n"
"    padding: 10px;\n"
"border: 1px solid #048cfc\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.findemp = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.findemp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.findemp.setObjectName("findemp")
        self.gridLayout.addWidget(self.findemp, 0, 0, 1, 1)
        self.findempbutton = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.findempbutton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("D:\\học đhoc\\Hoc ky 2\\Kỹ thuật lập trình\\3nguoi\\ui\\Quanly\\QuanLyNhanVien\\../../../images/Nhanvien/find.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.findempbutton.setIcon(icon4)
        self.findempbutton.setFlat(True)
        self.findempbutton.setObjectName("findempbutton")
        self.gridLayout.addWidget(self.findempbutton, 0, 1, 1, 1)
        self.listWidgetEmployee = QtWidgets.QListWidget(parent=self.groupBox_2)
        self.listWidgetEmployee.setObjectName("listWidgetEmployee")
        self.gridLayout.addWidget(self.listWidgetEmployee, 1, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_10.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.HomeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.HomeButton.setGeometry(QtCore.QRect(0, 0, 51, 31))
        self.HomeButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("D:\\học đhoc\\Hoc ky 2\\Kỹ thuật lập trình\\3nguoi\\ui\\Quanly\\QuanLyNhanVien\\../../../images/Home.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.HomeButton.setIcon(icon5)
        self.HomeButton.setObjectName("HomeButton")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 20, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(4, 140, 252);\n"
"border-radius: 15px;\n"
"padding: 5px;\n"
"background-color: rgb(211, 234, 255);")
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(-10, -10, 961, 751))
        self.label_6.setText("")
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_6.raise_()
        self.groupBox.raise_()
        self.groupBox_3.raise_()
        self.groupBox_2.raise_()
        self.HomeButton.raise_()
        self.label_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEditTen, self.lineEditId)
        MainWindow.setTabOrder(self.lineEditId, self.radNu)
        MainWindow.setTabOrder(self.radNu, self.radNam)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Skibidi Water"))
        self.label_9.setText(_translate("MainWindow", "Giới tính:"))
        self.radNu.setText(_translate("MainWindow", "Nữ"))
        self.radNam.setText(_translate("MainWindow", "Nam"))
        self.label_2.setText(_translate("MainWindow", "ID :"))
        self.label_5.setText(_translate("MainWindow", "Chức vụ:"))
        self.label_4.setText(_translate("MainWindow", "Ngày sinh:"))
        self.label.setText(_translate("MainWindow", "Tên:"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:696; color:#048cfc;\">Thông tin nhân viên</span></p></body></html>"))
        self.pushButtonSave.setText(_translate("MainWindow", "Lưu"))
        self.pushButtonNew.setText(_translate("MainWindow", "Mới"))
        self.pushButtonDelete.setText(_translate("MainWindow", "Xóa"))
        self.hienthibutton.setText(_translate("MainWindow", "Toàn bộ nhân viên"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:696; color:#048cfc;\">Tác vụ:</span></p></body></html>"))
        self.findemp.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:8pt;\">Nhập tên/id/chức vụ</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:696; color:#048cfc;\">Danh sách nhân viên</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:696; color:#048cfc;\">Quản lý nhân viên</span></p></body></html>"))
